name: Run Tests
on: push

jobs:
  build:
    name: Test LaTeX Bundle
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install BasicTeX
        run: brew install basictex

      - name: Install Cram
        run: pip install cram
