name: Run Tests
on: push

jobs:
  build:
    name: Test LaTeX Bundle
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install BasicTeX
        run: |
          brew install basictex

      - name: Install TeX packages
        run: |
          eval "$(/usr/libexec/path_helper)"
          sudo tlmgr update --self
          sudo tlmgr install --with-doc \
            biber  \
            biblatex \
            csquotes \
            ctablestack \
            datatool \
            framed \
            glossaries \
            latexmk \
            logreq \
            luacode \
            mfirstuc \
            substr \
            supertabular \
            texdoc \
            texdoctk \
            upmethodology \
            xfor \
            xstring

      - name: Install Cram
        run: pip install cram
