name: Run Tests
on: push

jobs:
  build:
    name: Test LaTeX Bundle
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install BasicTeX
        run: |
          brew install basictex

      - name: Install TeX packages
        run: |
          eval "$(/usr/libexec/path_helper)"
          sudo tlmgr update --self
          sudo tlmgr install --with-doc \
            biber  \
            biblatex \
            csquotes \
            ctablestack \
            datatool \
            framed \
            glossaries \
            latexmk \
            logreq \
            luacode \
            mfirstuc \
            substr \
            supertabular \
            texdoc \
            texdoctk \
            upmethodology \
            xfor \
            xstring

      - name: Install Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'

      - name: Install Cram
        run: pip install cram

      - name: Install Test Tools
        run: |
          brew install pidof
          brew install boost capnp google-sparsehash multimarkdown ninja ragel
          git clone --recursive https://github.com/textmate/textmate.git
          cd textmate
          ./configure && ninja gtm
          mv "$HOME/build/textmate/release/Applications/gtm/gtm" /usr/local/bin

      - name: Run Cram Tests
        run: make cramtests
